import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Urban Vogue",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children};</>;
}
