import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/components/header/header";
import NextAuthSessionProvider from "./providers/sessionProvider";
import { getServerSession } from "next-auth";
import { nextAuthOptions } from "./api/auth/[...nextauth]/route";
import ProductQuery from "./api/ProductQuery";
import { ChakraProvider } from "@chakra-ui/react";
import { AppProvider } from "./contexts/ContextApp";
import Cart from "./components/cart/cart";
import Favorites from "./components/favorites/favorites";

export const metadata: Metadata = {
  title: "Urban Vogue",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(nextAuthOptions);

  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
      </head>
      <body
        className={`flex w-full justify-center min-h-screen items-center`}
      >
        <AppProvider>
          <ChakraProvider>
            <NextAuthSessionProvider>
              <Cart />
              <Header href={session ? "/my-account" : "/login"} />
              {children}
              <Favorites />
            </NextAuthSessionProvider>
          </ChakraProvider>
        </AppProvider>
      </body>
    </html>
  );
}
